# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('niluscad', '0006_auto_20180423_2210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nilusfin', '0002_auto_20180401_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cont', models.IntegerField(verbose_name='Cod. Contrato')),
                ('data_contrato', models.DateTimeField(blank=True, null=True, verbose_name='Data Contrato')),
                ('vigencia', models.DateTimeField(blank=True, null=True, verbose_name='Vigência Contrato')),
                ('periodo_fat', models.CharField(choices=[('M', 'Meses'), ('S', 'Semanal'), ('Q', 'Quinzenal'), ('A', 'Anual')], default='M', max_length=1, verbose_name='Períodicidade de Faturamento')),
                ('modo_fat', models.CharField(choices=[('U', 'Valor Único na data Base'), ('S', 'Soma das ordens de serviço no período'), ('A', 'Avulso')], default='U', max_length=1, verbose_name='Modo de Faturamento')),
                ('gera_nfs', models.BooleanField(default=False, verbose_name='Gera nota fiscal de serviços?')),
                ('gera_boleto', models.BooleanField(default=False, verbose_name='Gera boleto bancário?')),
                ('vinculo_os', models.BooleanField(default=False, verbose_name='Permite vínculo nas ordens de serviço?')),
                ('obs_contrato', models.TextField(blank=True, verbose_name='Observações')),
                ('cadgeral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Cadgeral', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Company', verbose_name='Empresa')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Master')),
            ],
            options={
                'verbose_name': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Contratos_itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30, verbose_name='Item')),
                ('qtd', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('valor_text', models.CharField(max_length=20, verbose_name='Valor')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='niluscont.Contratos', verbose_name='Item')),
                ('indice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nilusfin.Indice')),
                ('user_cad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Criação')),
            ],
            options={
                'verbose_name': 'Contrato_item',
                'verbose_name_plural': 'Contratos_itens',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contratos_itens',
            unique_together=set([('contrato', 'item')]),
        ),
    ]
