# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscont', '0003_auto_20180502_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='qtd',
        ),
        migrations.AddField(
            model_name='contratos',
            name='dia_base',
            field=models.PositiveIntegerField(default=0, verbose_name='Dia Base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_unit_text',
            field=models.CharField(default=0, max_length=20, verbose_name='Valor unitário'),
            preserve_default=False,
        ),
    ]
