# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0003_cotacao_valor_cotacao_text'),
        ('niluscont', '0005_remove_contratos_valor_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='cotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nilusfin.Cotacao'),
        ),
    ]
