# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscont', '0006_contratos_cotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='data_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Data Contrato'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vigência Contrato'),
        ),
    ]
