# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0006_auto_20180423_2210'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niluscont', '0007_auto_20180505_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_os', models.PositiveIntegerField(verbose_name='Nº Ordem Serviço')),
                ('num_cont', models.IntegerField(verbose_name='Cod. Contrato')),
                ('data_os', models.DateField(blank=True, null=True, verbose_name='Data Contrato')),
                ('desc_item', models.CharField(max_length=40, verbose_name='Item')),
                ('valor_unit_text', models.CharField(max_length=20, verbose_name='Valor unitário')),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor')),
                ('cadgeral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Cadgeral', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Company', verbose_name='Empresa')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='niluscont.Contratos', verbose_name='Contrato')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Master')),
            ],
            options={
                'verbose_name': 'Ordens de Serviço',
            },
        ),
    ]
