# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscont', '0010_remove_ordemservico_num_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='ult_faturamento',
            field=models.DateField(blank=True, null=True, verbose_name='Ultimo Faturamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='situacao_fat',
            field=models.CharField(choices=[('A', 'Ativo'), ('F', 'Faturada')], default='A', max_length=1, verbose_name='Situação de faturamento'),
        ),
    ]
