# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niluscont', '0011_auto_20180515_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='ult_faturamento',
            new_name='prox_faturamento',
        ),
    ]
