# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramnfs',
            name='cnae',
            field=models.CharField(default=0, max_length=20, verbose_name='CNAE'),
            preserve_default=False,
        ),
    ]
