# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0003_auto_20180424_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramnfs',
            name='regime_trib',
            field=models.CharField(choices=[(None, 'Informe o regime'), ('M', 'Microempresa Municipal'), ('E', 'Estimativa'), ('S', 'Sociedade de Profissionais'), ('C', 'Cooperativa')], max_length=1, verbose_name='Regime especial de tributação'),
        ),
    ]
