# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0006_tmpfat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramnfs',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Company', unique=True, verbose_name='Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='paramnfs',
            unique_together=set([]),
        ),
    ]
