# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0007_auto_20180523_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramnfs',
            name='key_empresa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Key Enotas'),
        ),
        migrations.AlterField(
            model_name='paramnfs',
            name='regime_trib',
            field=models.CharField(choices=[(None, 'Informe o regime'), ('0', 'Normal'), ('1', 'Isenta'), ('2', 'Imune'), ('3', 'Suspenso/decisão judicial')], max_length=1, verbose_name='Regime especial de tributação'),
        ),
    ]
