# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nilusnfs', '0010_auto_20180524_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrosParametrosNFS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=100, verbose_name='Mensagem Erro')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usario Master')),
                ('paramnfs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nilusnfs.Paramnfs', verbose_name='Parametro Empresa')),
            ],
            options={
                'verbose_name': 'Erros Parametros NFS',
            },
        ),
    ]
