# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-02 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0013_auto_20180601_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramnfs',
            old_name='conf_sequencialNFe',
            new_name='conf_sequencialoteNFe',
        ),
    ]
