# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0023_auto_20180604_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramnfs',
            name='conf_enviaEmail',
            field=models.BooleanField(default=True, verbose_name='Envia email'),
        ),
    ]
