# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nilusfin', '0003_auto_20171106_2336'),
        ('niluscad', '0007_talhao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lan', models.IntegerField(verbose_name='Nº Registro')),
                ('dt_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data Lançamento')),
                ('dt_vencimento', models.DateField(verbose_name='Data Vencimento')),
                ('vlr_lancamento', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor do Lançamento')),
                ('valor_text', models.CharField(max_length=20, verbose_name='Valor')),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('B', 'Baixado'), ('C', 'Cancelado')], max_length=1, verbose_name='Situação')),
                ('data_baixa', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('tipo_lancamento', models.CharField(choices=[('R', 'Recebimento'), ('P', 'Pagamento')], max_length=1, verbose_name='Tipo')),
                ('c_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Ccusto', verbose_name='Centro de Custo')),
                ('cadgeral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Cadgeral', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='Empresa')),
                ('conta_finan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Contafinanceira', verbose_name='Conta Recebimento')),
                ('cotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Cotacao')),
                ('indice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Indice')),
                ('lancamento_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lancfinanceiros.Lancamentos', verbose_name='Lançamento Pai')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Master')),
                ('plr_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.PlanoFinan', verbose_name='Plano Financeiro')),
                ('propriety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Propriety', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='lancamentos',
            unique_together=set([('master_user', 'num_lan')]),
        ),
    ]
