# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0002_auto_20180315_2114'),
        ('lancfinanceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movtos_lancamentos',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='empresa'),
            preserve_default=False,
        ),
    ]
