# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Saldo'),
        ),
    ]
