# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='plr_financeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.PlanoFinan', verbose_name='Plano Financeiro'),
        ),
    ]
