# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lancfinanceiros', '0002_lancamentos_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='parcela',
            field=models.IntegerField(default=1, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='cadgeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Cadgeral', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='dt_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Vencimento'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='situacao',
            field=models.BooleanField(default=False, verbose_name='Baixado'),
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='propriety',
        ),
        migrations.AlterUniqueTogether(
            name='lancamentos',
            unique_together=set([('master_user', 'num_lan', 'parcela')]),
        ),
    ]
