# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0008_auto_20180308_2344'),
        ('lancfinanceiros', '0002_auto_20180308_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='movtos_lancamentos',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='plr_financeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.PlanoFinan', verbose_name='Plano Financeiro'),
        ),
    ]
