# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0003_auto_20180111_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='descricao',
            field=models.CharField(default=1, max_length=20, verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
