# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0004_auto_20180521_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='movtos_lancamentos',
            name='desc_movimento',
            field=models.CharField(max_length=200, null=True, verbose_name='Observação'),
        ),
    ]
