# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0005_auto_20180111_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='titulo',
            field=models.BooleanField(default=False, verbose_name='É Titulo'),
        ),
    ]
