# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0006_lancamentos_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamentos',
            name='cadgeral',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='cotacao',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='indice',
        ),
        migrations.RemoveField(
            model_name='lancamentos',
            name='saldo',
        ),
    ]
