# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0009_auto_20171227_2155'),
        ('nilusfin', '0008_auto_20171228_0042'),
        ('lancfinanceiros', '0007_auto_20180111_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='cadgeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Cadgeral', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='cotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Cotacao'),
        ),
        migrations.AddField(
            model_name='lancamentos',
            name='indice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Indice'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='descricao',
            field=models.CharField(max_length=70, null=True, verbose_name='Observação'),
        ),
    ]
