# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0008_auto_20180111_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Saldo'),
        ),
    ]
