# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0010_auto_20180114_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movtos_lancamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data Movimento')),
                ('vlr_movimento', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor do Lançamento')),
                ('desc_movimento', models.CharField(max_length=70, null=True, verbose_name='Observação')),
                ('tipo_movto', models.CharField(choices=[('C', 'Criação'), ('B', 'Baixa'), ('D', 'Desconto'), ('J', 'Juros'), ('M', 'Multa')], max_length=1, verbose_name='Tipo')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lancfinanceiros.Lancamentos', verbose_name='lancamento')),
            ],
            options={
                'verbose_name': 'Movimentos',
                'verbose_name_plural': 'Movimentos',
            },
        ),
    ]
