# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0011_movtos_lancamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movtos_lancamentos',
            name='dt_movimento',
            field=models.DateTimeField(verbose_name='Data Movimento'),
        ),
    ]
