# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0012_auto_20180121_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamentos',
            old_name='valor_original',
            new_name='saldo',
        ),
    ]
