# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0013_auto_20180121_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='descricao',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='tipo_lancamento',
            field=models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1, verbose_name='Tipo'),
        ),
    ]
