# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0011_auto_20180120_1056'),
        ('lancfinanceiros', '0014_auto_20180122_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='movtos_lancamentos',
            name='conta_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Contafinanceira', verbose_name='Conta Financeira'),
        ),
    ]
