# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0015_movtos_lancamentos_conta_financeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='data_baixa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='dt_lancamento',
            field=models.DateField(auto_now_add=True, verbose_name='Data Lançamento'),
        ),
        migrations.AlterField(
            model_name='movtos_lancamentos',
            name='dt_movimento',
            field=models.DateField(verbose_name='Data Movimento'),
        ),
    ]
