# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0016_auto_20180128_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='reaberto',
            field=models.BooleanField(default=False, verbose_name='Reaberto'),
        ),
    ]
