# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0017_lancamentos_reaberto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='c_custo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Ccusto', verbose_name='Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='conta_finan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nilusfin.Contafinanceira', verbose_name='Conta Recebimento'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='cotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nilusfin.Cotacao'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='indice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nilusfin.Indice'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='plr_financeiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.PlanoFinan', verbose_name='Plano Financeiro'),
        ),
        migrations.AlterField(
            model_name='movtos_lancamentos',
            name='conta_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nilusfin.Contafinanceira', verbose_name='Conta Financeira'),
        ),
        migrations.AlterField(
            model_name='movtos_lancamentos',
            name='lancamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lancfinanceiros.Lancamentos', verbose_name='lancamento'),
        ),
    ]
