# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 04:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lancfinanceiros', '0019_auto_20180224_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='movtos_lancamentos',
            name='master_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Master'),
        ),
    ]
