# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 04:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0020_movtos_lancamentos_master_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movtos_lancamentos',
            name='master_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Master'),
            preserve_default=False,
        ),
    ]
