# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0021_auto_20180224_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='movtos_lancamentos',
            name='sinal',
            field=models.CharField(default=1, max_length=3, verbose_name='Sinal da Conta'),
            preserve_default=False,
        ),
    ]
