# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0022_movtos_lancamentos_sinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movtos_lancamentos',
            name='conta_financeira',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Contafinanceira', verbose_name='Conta Financeira'),
        ),
    ]
