# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nilusfin', '0003_auto_20171106_2336'),
        ('niluscad', '0003_auto_20171107_0038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recebiveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rec', models.IntegerField(verbose_name='Nº Registro')),
                ('dt_lancamento', models.DateTimeField(auto_now_add=True, verbose_name='Data Lançamento')),
                ('dt_vencimento', models.DateTimeField(verbose_name='Data Vencimento')),
                ('vlr_lancamento', models.DecimalField(decimal_places=4, max_digits=13, verbose_name='Valor do Lançamento')),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('B', 'Baixado'), ('C', 'Cancelado')], max_length=1, verbose_name='Situação')),
                ('data_baixa', models.DateTimeField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('c_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Ccusto', verbose_name='Centro de Custo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Cadgeral', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='Empresa')),
                ('cotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Cotacao')),
                ('indice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Indice')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Master')),
                ('plr_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.PlanoFinan', verbose_name='Plano Financeiro')),
                ('propriety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Propriety', verbose_name='Propriedade')),
            ],
        ),
    ]
