# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebiveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebiveis',
            name='dt_vencimento',
            field=models.DateField(verbose_name='Data Vencimento'),
        ),
    ]
