# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recebiveis', '0002_auto_20171108_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebiveis',
            name='lancamento_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recebiveis.Recebiveis', verbose_name='Lançamento Pai'),
        ),
    ]
