# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebiveis', '0004_auto_20171108_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebiveis',
            name='vlr_lancamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor do Lançamento'),
        ),
    ]
