# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recebiveis', '0005_auto_20171108_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebiveis',
            name='valor_text',
            field=models.CharField(default=0, max_length=20, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
