# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recebiveis', '0006_recebiveis_valor_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebiveis',
            name='lancamento_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recebiveis.Recebiveis', verbose_name='Lançamento Pai'),
        ),
    ]
