# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0003_auto_20171106_2336'),
        ('recebiveis', '0007_auto_20171120_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebiveis',
            name='conta_receb',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Contafinanceira', verbose_name='Conta Recebimento'),
            preserve_default=False,
        ),
    ]
