# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recebiveis', '0008_recebiveis_conta_receb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recebiveis',
            options={'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
        migrations.AddField(
            model_name='recebiveis',
            name='tipo_lancamento',
            field=models.CharField(choices=[('R', 'Recebimento'), ('P', 'Pagamento')], default=1, max_length=1, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recebiveis',
            unique_together=set([('master_user', 'num_rec')]),
        ),
    ]
