# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0012_auto_20180606_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadgeral',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
    ]
