# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180315_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qtd_propriety',
        ),
    ]
