# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lancfinanceiros', '0003_auto_20180401_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentos',
            name='c_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='niluscad.Ccusto', verbose_name='Centro de Custo'),
        ),
    ]
