# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 02:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niluscad', '0006_auto_20180423_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paramnfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_param', models.IntegerField(verbose_name='Cod. Empresa')),
                ('cd_srv_padrao', models.CharField(max_length=20, verbose_name='Cod. Serviço Padrão')),
                ('desc_srv', models.CharField(max_length=60, verbose_name='Descrição do Serviço')),
                ('aliquota_iss', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='Aliquota')),
                ('it_lista_srv', models.CharField(max_length=20, verbose_name='Item da lista de serviço')),
                ('simples_nac', models.BooleanField(default=False, verbose_name='Optante Simples Nacional')),
                ('incent_cult', models.BooleanField(default=False, verbose_name='Incentivador Cultural')),
                ('regime_trib', models.CharField(choices=[('M', 'Microempresa Municipal'), ('E', 'Estimativa'), ('S', 'Sociedade de Profissionais'), ('C', 'Cooperativa')], max_length=1, verbose_name='Regime especial de tributação')),
                ('certificado_pfx', models.FileField(blank=True, upload_to='certificados', verbose_name='Certificado')),
                ('certificado_nome', models.CharField(blank=True, max_length=50, verbose_name='Nome Certificado')),
                ('certificado_senha', models.CharField(max_length=50, verbose_name='Nome Certificado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Company', verbose_name='Empresa')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usario Master')),
            ],
            options={
                'verbose_name': 'Parametros NFS',
            },
        ),
    ]
