# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0002_paramnfs_cnae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramnfs',
            name='certificado_pfx',
            field=models.FileField(blank=True, upload_to='images', verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='paramnfs',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Company', unique=True, verbose_name='Empresa'),
        ),
    ]
