# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscont', '0013_auto_20180516_2317'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nilusnfs', '0005_auto_20180501_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpFat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo')),
                ('data_fat', models.DateField(verbose_name='Data Faturamento')),
                ('situacao', models.BooleanField(default=False, verbose_name='Faturado')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscont.Contratos', verbose_name='Contrato')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usario Master')),
                ('os', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscont.OrdemServico', verbose_name='O.S')),
            ],
            options={
                'verbose_name': 'PendenteFaturamento',
            },
        ),
    ]
