# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0009_paramnfs_pendencias_cad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramnfs',
            old_name='pendencias_cad',
            new_name='habilitada_faturamento',
        ),
    ]
