# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-29 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0008_auto_20180526_0015'),
        ('nilusnfs', '0011_errosparametrosnfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpfat',
            name='cadgeral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Cadgeral', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='tmpfat',
            name='vlr_fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Fatura'),
        ),
    ]
