# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0012_auto_20180528_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramnfs',
            name='conf_senhaUsuarioAcesso',
            field=models.CharField(default=1, max_length=30, verbose_name='Senha site prefeitura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paramnfs',
            name='conf_sequenciaNFE',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequencia NFS-e'),
        ),
        migrations.AddField(
            model_name='paramnfs',
            name='conf_sequencialNFe',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequencia Lote NFe'),
        ),
        migrations.AddField(
            model_name='paramnfs',
            name='conf_serieNFE',
            field=models.CharField(default='NF', max_length=4, verbose_name='Serie NFS-e'),
        ),
        migrations.AddField(
            model_name='paramnfs',
            name='conf_usuarioAcesso',
            field=models.CharField(default=1, max_length=30, verbose_name='Usuário site prefeitura'),
            preserve_default=False,
        ),
    ]
