# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-03 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0014_auto_20180601_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramnfs',
            name='conf_serieNFE',
            field=models.CharField(default='1', max_length=4, verbose_name='Serie NFS-e'),
        ),
    ]
