# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-03 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0008_auto_20180526_0015'),
        ('nilusnfs', '0015_auto_20180603_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpfat',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
