# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-03 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0008_auto_20180526_0015'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nilusnfs', '0016_tmpfat_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasFiscais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_nf', models.PositiveIntegerField(verbose_name='Nº Nota Fiscal')),
                ('data_emissao', models.DateField(verbose_name='Emissão')),
                ('vlr_nota', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Nota')),
                ('obs_nota', models.CharField(max_length=1000, verbose_name='Observacoes')),
                ('id_key', models.CharField(max_length=100, verbose_name='Key Enotas')),
                ('link_pdf', models.CharField(max_length=1000, verbose_name='Link PDF')),
                ('link_xml', models.CharField(max_length=1000, verbose_name='Link XML')),
                ('desc_status_nfs', models.CharField(max_length=20, verbose_name='Status NFS')),
                ('motivoStatus', models.CharField(max_length=300, verbose_name='Motivo Status')),
                ('cadgeral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Cadgeral', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='Empresa')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usario Master')),
            ],
            options={
                'verbose_name': 'Notas Faiscais',
            },
        ),
        migrations.AlterField(
            model_name='tmpfat',
            name='cadgeral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Cadgeral', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='tmpfat',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscont.Contratos', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='tmpfat',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscont.OrdemServico', verbose_name='O.S'),
        ),
    ]
