# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0017_auto_20180603_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasfiscais',
            options={'verbose_name': 'Notas Fiscais'},
        ),
        migrations.AlterField(
            model_name='notasfiscais',
            name='num_nf',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº Nota Fiscal'),
        ),
    ]
