# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0018_auto_20180603_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasfiscais',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Emissão'),
        ),
    ]
