# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0019_auto_20180603_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasfiscais',
            name='desc_status_nfs',
            field=models.CharField(max_length=100, verbose_name='Status NFS'),
        ),
    ]
