# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0020_auto_20180603_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasfiscais',
            name='id_origem',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Externo'),
        ),
        migrations.AddField(
            model_name='notasfiscais',
            name='tipo_origem',
            field=models.CharField(blank=True, choices=[('O', 'OrdemServico'), ('C', 'Contrato')], max_length=1, null=True, verbose_name='tipo_origem'),
        ),
    ]
