# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0021_auto_20180604_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notasfiscais',
            old_name='tipo_origem',
            new_name='tipo',
        ),
    ]
