# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0022_auto_20180604_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasfiscais',
            name='tipo_origem',
            field=models.CharField(blank=True, choices=[('O', 'OrdemServico'), ('C', 'Contrato')], max_length=1, null=True, verbose_name='tipo_origem'),
        ),
        migrations.AlterField(
            model_name='notasfiscais',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='tipo registro'),
        ),
    ]
