# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0024_paramnfs_conf_enviaemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasfiscais',
            name='data_emissao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emissão'),
        ),
    ]
