# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-14 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusnfs', '0027_auto_20180713_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasfiscais',
            name='envio_concluido',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Envio Concluido'),
        ),
    ]
