# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel_user',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone'),
        ),
    ]
