# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0009_planofinan'),
        ('accounts', '0002_user_tel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_p',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='Empresa Padrão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='propriety_p',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Propriety', verbose_name='Propriedade Padrão'),
            preserve_default=False,
        ),
    ]
