# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-04 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171103_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='Empresa Padrão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='propriety_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Propriety', verbose_name='Propriedade Padrão'),
        ),
    ]
