# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180114_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='niluscad.Company', verbose_name='Empresa Padrão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='propriety_p',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niluscad.Propriety', verbose_name='Propriedade Padrão'),
        ),
    ]
