# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilusCadastro', models.BooleanField(default=False, verbose_name='Cadastros')),
                ('nilusFinanceiro', models.BooleanField(default=False, verbose_name='Financeiro')),
                ('nilusCompras', models.BooleanField(default=False, verbose_name='Compras')),
                ('nilusProducao', models.BooleanField(default=False, verbose_name='Producao')),
                ('nilusMaquinas', models.BooleanField(default=False, verbose_name='Máquinas')),
                ('nilusFiscalCont', models.BooleanField(default=False, verbose_name='Fiscal e Contábil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
