# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusadm', '0002_sequenciais_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciais',
            name='indice',
            field=models.IntegerField(default=0, verbose_name='Seq Indice'),
        ),
    ]
