# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusadm', '0002_sequenciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciais',
            name='ccusto',
            field=models.IntegerField(default=0, verbose_name='Seq Cad. Ccusto'),
        ),
    ]
