# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusadm', '0003_sequenciais_ccusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciais',
            name='planofinan',
            field=models.IntegerField(default=0, verbose_name='Seq PlanoFinan'),
        ),
    ]
