# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusadm', '0003_sequenciais_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciais',
            name='recebiveis',
            field=models.IntegerField(default=0, verbose_name='Seq Tit. Receber'),
        ),
    ]
