# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusadm', '0003_auto_20180501_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciais',
            name='ordensservico',
            field=models.IntegerField(default=0, verbose_name='Seq O.S'),
        ),
    ]
