# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusadm', '0004_sequenciais_recebiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenciais',
            name='lanc_financeiros',
            field=models.IntegerField(default=0, verbose_name='Seq Lancamento Financeiro'),
        ),
    ]
