# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niluscad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupodre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_grupodre', models.IntegerField(verbose_name='Código')),
                ('descricao', models.CharField(max_length=20, verbose_name='Nome Grupo')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem no relatório')),
                ('sinal', models.CharField(choices=[(None, 'Informe o calculo'), ('+', 'Soma'), ('-', 'Subtrai')], max_length=1, verbose_name='Sinal Conta')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Master')),
            ],
            options={
                'verbose_name': 'Grupo DRE',
                'verbose_name_plural': 'Grupos DRE',
            },
        ),
        migrations.AddField(
            model_name='planofinan',
            name='grupodre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano_financeiro', to='niluscad.Grupodre', verbose_name='Grupo Dre'),
        ),
        migrations.AlterUniqueTogether(
            name='grupodre',
            unique_together=set([('master_user', 'num_grupodre')]),
        ),
    ]
