# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planofinan',
            name='descricao',
            field=models.CharField(max_length=60, verbose_name='Descricão'),
        ),
    ]
