# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0001_initial'),
        ('niluscad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planofinan',
            name='grupodre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Grupodre', verbose_name='Grupo Dre'),
            preserve_default=False,
        ),
    ]
