# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0002_auto_20180315_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupodre',
            name='sinal',
            field=models.CharField(blank=True, choices=[(None, 'Informe o tipo'), ('+', 'Receita'), ('-', 'Despesa')], max_length=1, null=True, verbose_name='Grupo Tipo'),
        ),
    ]
