# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0002_auto_20171028_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriety',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço'),
        ),
    ]
