# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0002_auto_20171106_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usario Master'),
        ),
    ]
