# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 02:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niluscad', '0003_auto_20171107_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccusto',
            options={'verbose_name': 'C. Custo', 'verbose_name_plural': 'C. Custos'},
        ),
        migrations.AlterModelOptions(
            name='planofinan',
            options={'verbose_name': 'Plano Financeiro', 'verbose_name_plural': 'Plano Financeiro'},
        ),
        migrations.AlterUniqueTogether(
            name='ccusto',
            unique_together=set([('master_user', 'num_ccusto')]),
        ),
        migrations.AlterUniqueTogether(
            name='planofinan',
            unique_together=set([('master_user', 'num_plfin')]),
        ),
    ]
