# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0004_auto_20180308_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodre',
            name='ordem',
            field=models.PositiveIntegerField(default=1, verbose_name='Ordem no relatório'),
            preserve_default=False,
        ),
    ]
