# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0004_auto_20171108_0043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([]),
        ),
    ]
