# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0005_auto_20171120_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriety',
            name='area',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Área M²'),
        ),
    ]
