# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0005_auto_20180319_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='insc_est',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='company',
            name='insc_mun',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal'),
        ),
    ]
