# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0006_auto_20180423_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ibge_mun',
            field=models.IntegerField(blank=True, null=True, verbose_name='IBGE Cidade'),
        ),
        migrations.AddField(
            model_name='company',
            name='ibge_uf',
            field=models.IntegerField(blank=True, null=True, verbose_name='IBGE UF'),
        ),
    ]
