# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 02:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niluscad', '0006_auto_20171029_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ccusto', models.IntegerField(verbose_name='Código')),
                ('descricao', models.CharField(max_length=60, verbose_name='Descricao')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uusario Master')),
            ],
        ),
    ]
