# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0006_auto_20180308_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planofinan',
            name='grupodre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Grupodre', verbose_name='Grupo Dre'),
        ),
    ]
