# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niluscad', '0007_ccusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriety',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='Empresa Vinculada'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='propriety',
            unique_together=set([('master_user', 'num_propriety', 'company'), ('master_user', 'num_propriety'), ('master_user', 'ie')]),
        ),
    ]
