# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0007_talhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talhao',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Área'),
        ),
    ]
