# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0008_auto_20180308_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodre',
            name='sinal',
            field=models.CharField(choices=[(None, 'Informe o sinal'), ('+', 'Soma'), ('-', 'Subtrai')], default=1, max_length=1, verbose_name='Sinal Conta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planofinan',
            name='grupodre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano_financeiro', to='niluscad.Grupodre', verbose_name='Grupo Dre'),
        ),
    ]
