# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0008_auto_20171220_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planofinan',
            name='sinal',
            field=models.CharField(choices=[(None, 'Informe o sinal'), ('D', 'Despesas'), ('R', 'Receitas')], max_length=1, verbose_name='Sinal Conta'),
        ),
    ]
