# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0009_auto_20171227_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriety',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='niluscad.Company', verbose_name='Empresa Vinculada'),
        ),
    ]
