# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-06 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0011_auto_20180606_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadgeral',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='propriety',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
    ]
