# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 00:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contafinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_conta', models.IntegerField(verbose_name='Código')),
                ('conta_bancaria', models.BooleanField(default=False, verbose_name='Conta Bancária?')),
                ('agencia', models.CharField(blank=True, max_length=5, null=True, verbose_name='Agencia')),
                ('conta', models.CharField(blank=True, max_length=12, null=True, verbose_name='Conta')),
                ('descricao', models.CharField(max_length=60, verbose_name='Nome Conta')),
                ('usa_limite', models.BooleanField(default=False, verbose_name='Utiliza Limite')),
                ('vlr_limite', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Valor Limite')),
                ('vlr_limite_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Limite')),
                ('conta_pagamento', models.BooleanField(default=False, verbose_name='Conta de Pagamento?')),
                ('conta_recebimento', models.BooleanField(default=False, verbose_name='Conta de Recebimento?')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Master')),
            ],
            options={
                'verbose_name': 'Contas',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_indice', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('valor_cotacao', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True, verbose_name='Valor')),
                ('cotacao_padrao', models.BooleanField(default=False, verbose_name='Cotação Padrão')),
            ],
            options={
                'verbose_name': 'Cotacao',
                'verbose_name_plural': 'Cotações',
            },
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_indice', models.IntegerField(verbose_name='Código')),
                ('descricao', models.CharField(max_length=20, verbose_name='Nome Indice')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Simbolo')),
                ('indice_padrao', models.BooleanField(default=False, verbose_name='Indice Padrao')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uusario Master')),
            ],
            options={
                'verbose_name': 'Indice',
                'verbose_name_plural': 'Indices',
            },
        ),
        migrations.AddField(
            model_name='cotacao',
            name='indice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Indice', verbose_name='Indice'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='user_cad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Criação'),
        ),
        migrations.AlterUniqueTogether(
            name='indice',
            unique_together=set([('master_user', 'num_indice')]),
        ),
        migrations.AlterUniqueTogether(
            name='cotacao',
            unique_together=set([('indice', 'data_indice')]),
        ),
        migrations.AlterUniqueTogether(
            name='contafinanceira',
            unique_together=set([('master_user', 'num_conta')]),
        ),
    ]
