# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contafinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_conta', models.IntegerField(verbose_name='Código')),
                ('agencia', models.CharField(blank=True, max_length=5, null=True, verbose_name='Agencia')),
                ('conta', models.CharField(blank=True, max_length=12, null=True, verbose_name='Conta')),
                ('descricao', models.CharField(max_length=60, verbose_name='Nome Conta')),
                ('usa_limite', models.BooleanField(default=False, verbose_name='Utiliza Limite')),
                ('vlr_limite', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Valor Limite')),
                ('conta_pagamento', models.BooleanField(default=False, verbose_name='Conta de Pagamento?')),
                ('conta_recebimento', models.BooleanField(default=False, verbose_name='Conta de Recebimento?')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uusario Master')),
            ],
        ),
    ]
