# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='indice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nilusfin.Indice', verbose_name='Indice'),
        ),
    ]
