# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nilusfin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupodre',
            name='num_grupodre',
            field=models.IntegerField(default=0, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='grupodre',
            unique_together=set([('master_user', 'num_grupodre')]),
        ),
    ]
