# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nilusfin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_indice', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('valor_cotacao', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True, verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_indice', models.IntegerField(verbose_name='Código')),
                ('descricao', models.CharField(max_length=20, verbose_name='Nome Indice')),
                ('simbolo', models.CharField(max_length=5, verbose_name='Simbolo')),
                ('master_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uusario Master')),
            ],
        ),
        migrations.AddField(
            model_name='cotacao',
            name='indice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Indice', verbose_name='Indice'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uusario Master'),
        ),
    ]
