# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupodre',
            name='master_user',
        ),
        migrations.DeleteModel(
            name='Grupodre',
        ),
    ]
