# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-04 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0002_auto_20180401_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='valor_cotacao_text',
            field=models.CharField(default=0, max_length=20, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
