# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nilusfin', '0002_auto_20171106_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indice',
            options={'verbose_name': 'Indice', 'verbose_name_plural': 'Indices'},
        ),
        migrations.AlterUniqueTogether(
            name='indice',
            unique_together=set([('master_user', 'num_indice')]),
        ),
    ]
