# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niluscad', '0004_auto_20180308_2202'),
        ('nilusfin', '0002_auto_20180307_2243'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupodre',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='grupodre',
            name='master_user',
        ),
        migrations.DeleteModel(
            name='Grupodre',
        ),
    ]
