# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0003_auto_20171106_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contafinanceira',
            name='conta_bancaria',
            field=models.BooleanField(default=False, verbose_name='Conta Bancária?'),
        ),
    ]
