# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0004_contafinanceira_conta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contafinanceira',
            name='vlr_limite_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Limite'),
        ),
    ]
