# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nilusfin', '0005_contafinanceira_vlr_limite_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contafinanceira',
            options={'verbose_name': 'Contas', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterModelOptions(
            name='cotacao',
            options={'verbose_name': 'Cotacao', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AddField(
            model_name='cotacao',
            name='user_cad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contafinanceira',
            name='master_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Master'),
        ),
        migrations.AlterUniqueTogether(
            name='contafinanceira',
            unique_together=set([('master_user', 'num_conta')]),
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='master_user',
        ),
        migrations.AlterUniqueTogether(
            name='cotacao',
            unique_together=set([('indice', 'data_indice', 'valor_cotacao')]),
        ),
    ]
