# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0006_auto_20171227_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='indice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nilusfin.Indice', verbose_name='Indice'),
        ),
    ]
