# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0007_auto_20171227_2225'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cotacao',
            unique_together=set([]),
        ),
    ]
