# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0008_auto_20171228_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='cotacao_padrao',
            field=models.BooleanField(default=False, verbose_name='Cotação Padrão'),
        ),
        migrations.AddField(
            model_name='indice',
            name='indice_padrao',
            field=models.BooleanField(default=False, verbose_name='Indice Padrao'),
        ),
    ]
