# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0009_auto_20180114_1743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cotacao',
            unique_together=set([('indice', 'data_indice')]),
        ),
    ]
