# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_p', models.IntegerField(verbose_name='Empresa padrão PK')),
                ('property_p', models.IntegerField(verbose_name='Propriedade Padrão PK')),
                ('num_company', models.IntegerField(verbose_name='Empresa padrao Cod. Int')),
                ('num_propriety', models.IntegerField(verbose_name='Propriedade padrao Cod. Int')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Instancia',
                'verbose_name_plural': 'Instancias',
            },
        ),
    ]
