# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20171105_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancia',
            old_name='company_p',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='instancia',
            old_name='property_p',
            new_name='propriety',
        ),
        migrations.AlterField(
            model_name='instancia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
