# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20171105_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancia',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Company', verbose_name='Empresa padrão'),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='propriety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='niluscad.Propriety', verbose_name='Propriedade Padrão'),
        ),
    ]
