# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20171105_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancia',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niluscad.Company', verbose_name='Empresa padrão'),
        ),
        migrations.AlterField(
            model_name='instancia',
            name='propriety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='niluscad.Propriety', verbose_name='Propriedade Padrão'),
        ),
    ]
