# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilusadm', '0002_sequenciais_paramnfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='nilusContratos',
            field=models.BooleanField(default=False, verbose_name='Contratos'),
        ),
        migrations.AddField(
            model_name='sequenciais',
            name='contratos',
            field=models.IntegerField(default=0, verbose_name='Seq Contratos'),
        ),
    ]
