# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nilusfin', '0002_auto_20180401_2221'),
        ('niluscad', '0006_auto_20180423_2210'),
        ('niluscont', '0002_auto_20180501_2351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contratos_itens',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contratos_itens',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='contratos_itens',
            name='indice',
        ),
        migrations.RemoveField(
            model_name='contratos_itens',
            name='user_cad',
        ),
        migrations.AddField(
            model_name='contratos',
            name='indice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nilusfin.Indice'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='item',
            field=models.CharField(default=0, max_length=40, verbose_name='Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='qtd',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='contratos',
            unique_together=set([('cadgeral', 'item')]),
        ),
        migrations.DeleteModel(
            name='Contratos_itens',
        ),
    ]
