# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-08 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('niluscont', '0009_ordemservico_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='num_cont',
        ),
    ]
