# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niluscont', '0012_auto_20180516_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='prestador',
            field=models.IntegerField(null=True, verbose_name='Cod. Prestador'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='prox_faturamento',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Faturamento'),
        ),
    ]
